name: Bug report
description: Create a report about something that is not working
labels:
  - bug
  - triage
assignees:
  - beauchama
body:
  - type: checkboxes
    id: is-bug-exists
    attributes:
      label: Is there an existing bug for this?
      description: >-
        Please search to see if an issue already exists for the bug you encountered ([pulsewave/issues](https://github.com/beauchama/pulsewave/issues)).
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    id: package-version
    attributes:
      label: Package version
      description: Which package cause the bug and his version
      placeholder: Pulsewave.Extensions.Linq-1.0.0
    validations:
      required: true
  - type: input
    id: net-version
    attributes:
      label: .NET Version
      description: Run dotnet --version
      placeholder: 8.0.0
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: >-
        We ❤ code! Point us to a [minimalistic project which reproduces this issue (repro)](https://github.com/beauchama/pulsewave/blob/main/docs/repro.md) hosted in a public GitHub repo.
  - type: textarea
    id: anything-else
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
